- epanet_matlab_toolkit/epanet.m
Comment lines have been added in the following functions:
getNodeTankVolume
getNodeTankMaximumWaterVolume
setLinkBulkReactionCoeff
setLinkWallReactionCoeff
> Help-Comments added in 4 function

- epanet_matlab_toolkit/epanet.m
Functions with new help-text:
1) getLinkFlows
2) getLinkVelocity
3) getLinkHeadloss
4) getLinkStatus
5) getLinkPumpState
6) getLinkSettings
7) getLinkEnergy
8) getLinkActualQuality
9) getLinkPumpEfficiency
10) getLinkPumpPower
> Help-text added in 10 functions

- epanet_matlab_toolkit/epanet.m
Functions with a new help-text:
1) getNodeNameID
2) getNodeReservoirNameID
3) getNodeJunctionNameID
4) getNodeReservoirIndex
5) getNodeJunctionIndex
6) getNodeType
7) getNodeTypeIndex
8) getNodesInfo
9) getNodeElevations
10) getNodeComment
> Help-text added in 10 functions (2)

- epanet_matlab_toolkit/epanet.m
1) getLinkType
2) getLinkTypeIndex
3) getLinksInfo
4) getLinkDiameter
5) getLinkLength
6) getLinkRoughnessCoeff
7) getLinkMinorLossCoeff
8) getLinkInitialStatus
9) getLinkInitialSetting
10) getLinkBulkReactionCoeff
11) getLinkWallReactionCoeff
12) getLinkFlows
> Updated 12 function help-texts

- epanet_matlab_toolkit/epanet.m
Functions with updated help text:
1) getLinkVelocity
2) getLinkHeadloss
3) getLinkStatus
4) getLinkPumpState
5) getLinkSettings
6) getLinkEnergy
7) getLinkActualQuality
8) getLinkPumpEfficiency
> Updated 8 (dynamic) functions help-text

- epanet_matlab_toolkit/epanet.m
1) getNodeNameID
2) getNodeReservoirNameID
3) getNodeJunctionNameID
4) getNodeIndex
5) getNodeReservoirIndex
6) getNodeJunctionIndex
7) getNodeType
8) getNodeTypeIndex
9) getNodesInfo
> Help-texts in 9 (getNode) functions have been updated

- epanet_matlab_toolkit/epanet.m
1) getLinkPumpPower
2) getLinkPumpHCurve
3) getLinkPumpECurve
4) getLinkPumpECost
5) getLinkPumpEPat
6) getLinkPumpPatternIndex
7) getLinkPumpPatternNameID
> Updated 7 functions(getLinkPump) help-text

- epanet_matlab_toolkit/epanet.m
Functions with help-text updated:
1) getNodeActualDemand
2) getNodeActualDemandSensingNodes
3) getNodeHydaulicHead
4) getNodePressure
5) getNodeActualQuality
6) getNodeMassFlowRate
7) getNodeActualQualitySensingNodes
> Help-texts updated in 7 (getNode dynamic)functions

- epanet_matlab_toolkit/epanet.m
1) getNodeElevations
2) getDemandModel
3) getNodeJunctionDemandName
4) getNodeComment
5) setNodeComment
6) getTitle
7) getNodeBaseDemands
8) getNodeDemandCategoriesNumber
9) getNodeDemandPatternIndex
10) getNodeDemandPatternNameID
> Help-texts in 10 functions have been updated

- epanet_matlab_toolkit/epanet.m
1) getStatistic
2) getNodePatternIndex
3) getNodeEmitterCoeff
4) getNodeInitialQuality
5) getNodeSourceQuality
6) getNodeSourcePatternIndex
7) getNodeSourceTypeIndex
8) getNodeSourceType
9) getNodeTankInitialLevel
> Help-texts in 9 functions have been updated (2)

- epanet_matlab_toolkit/epanet.m
1) getNodeTankInitialWaterVolume
2) getNodeTankMixiningModel
3) getNodeTankMixingModelCode
4) getNodeTankMixingModelType
5) getNodeTankMixZoneVolume
6) getNodeTankDiameter
7) getNodeTankMinimumWaterVolume
8) getNodeTankVolumeCurveIndex
9) getNodeTankMinimumWaterLevel
10) getNodeTankMaximumWaterLevel
> Help-texts in 10 functions(getNodeTank) have been updated (3)

- README.md
- epanet_matlab_toolkit/epanet.m
New functions:
1) addNodeJunctionDemand
2) ENadddemand
3) getNodeJunctionIndices
I have also changed a line in the function 'getNodeJunctionDemandName' in order to display only the demand name for junctions and not for reservoirs and/or tanks.
> New Functions

- README.md
- epanet_matlab_toolkit/epanet.m
1) setOptionsGlobalEffic
2) setOptionsGlobalPrice
3) setOptionsGlobalPattern
4) setOptionsDemandCharge
> 4 new functions(setOptions)

- README.md
- epanet_matlab_toolkit/epanet.m
1) getOptionsSpecificGravity
2) getOptionsSpecificViscosity
3) getOptionsExtraTrials
4) getOptionsCheckFrequency
5) getOptionsMaximumCheck
6) setOptionsSpecificGravity
7) setOptionsSpecificViscosity
8) setOptionsExtraTrials
9) setOptionsCheckFrequency
10) setOptionsMaximumCheck
> 10 new function(getOptions & setOptions)

- README.md
- epanet_matlab_toolkit/epanet.m
getOptions:
1) getOptionsDampLimit
2) getOptionsSpecificDiffusivity
3) getOptionsPipeBulkReactionOrder
4) getOptionsPipeWallReactionOrder
5) getOptionsTankBulkReactionOrder
6) getOptionsLimitingConcentration
setOptions:
1) setOptionsDampLimit
2) setOptionsSpecificDiffusivity
3) setOptionsPipeBulkReactionOrder
4) setOptionsPipeWallReactionOrder
5) setOptionsTankBulkReactionOrder
6) setOptionsLimitingConcentration
> 12 new functions(getOptions & setOptions)

- epanet_matlab_toolkit/epanet.m
1) getOptionsDemandCharge
2) getOptionsSpecificGravity
3) getOptionsSpecificViscosity
4) getOptionsExtraTrials
5) getOptionsCheckFrequency
6) getOptionsMaximumCheck
7) getOptionsDampLimit
8) getOptionsSpecificDiffusivity
9) getOptionsPipeBulkReactionOrder
10) getOptionsPipeWallReactionOrder
11) getOptionsTankBulkReactionOrder
12) getOptionsLimitingConcentration
> 12 updated help-text

- epanet_matlab_toolkit/epanet.m
1) setOptionsMaxTrials
2) setOptionsAccuracyValue
3) setOptionsQualityTolerance
4) setOptionsEmitterExponent
5) setOptionsPatternDemandMultiplier
6) setOptionsHeadLossFormula
7) setOptionsGlobalEffic
8) setOptionsGlobalPrice
9) setOptionsGlobalPattern
10) setOptionsDemandCharge
> 10 new help-text(in setOption)

- epanet_matlab_toolkit/epanet.m
Functions with new help-text:
1) setOptionsSpecificGravity
2) setOptionsSpecificViscosity
3) setOptionsExtraTrials
4) setOptionsCheckFrequency
5) setOptionsMaximumCheck
6) setOptionsDampLimit
7) setOptionsSpecificDiffusivity
8) setOptionsPipeBulkReactionOrder
9) setOptionsPipeWallReactionOrder
10) setOptionsTankBulkReactionOrder
11) setOptionsLimitingConcentration
> 11 new help-text(in setOption)

- epanet_matlab_toolkit/epanet.m
Functions with new help-text:
1) getOptionsMaxTrials
2) getOptionsAccuracyValue
3) getOptionsQualityTolerance
4) getOptionsEmitterExponent
5) getOptionsPatternDemandMultiplier
6) getOptionsHeadError
7) getOptionsFlowChange
8) getOptionsHeadLossFormula
9) getOptionsGlobalEffic
10) getOptionsGlobalPrice
11) getOptionsGlobalPattern
2 new functions:
1) setOptionsHeadError
2) setOptionsFlowChange
> 11 new help text & 2 new functions(setOption)

- README.md
- epanet_matlab_toolkit/epanet.m
1) setCurveNameID
2) ENsetcurveid
> New function

- epanet_matlab_toolkit/epanet.m
1) deleteNodeJunctionDemand
2) ENdeletedemand
> New function (1)

- epanet_matlab_toolkit/epanet.m
1. getRules
2. setRuleThenAction
3. setRuleElseAction
4. setRulePremise
5. setRulePremiseObejctNameID
6. setRulePremiseStatus
> Updated 6 functions

- epanet_matlab_toolkit/epanet.m
Function added in private: set_Node_Link
Functions updated: 
setNodeNameID (Error was displayed before the update)
6 setLinkPump...
9 setNodeTank...
Help - texts updated:
1) setNodeEmitterCoeff
2) setNodeInitialQuality
> Added 1 function. Updated 16 functions. Updated 2 help - texts.

- epanet_matlab_toolkit/epanet.m
The function setTimeStartTime does not work. Error 251 shows up.
> Added 8 help - texts

- README.md
- epanet_matlab_toolkit/epanet.m
Functions that have been updated:
1) addBinNodeJunction
2) addBinNodeReservoir
3) addBinNodeTank
4) addBinNode(Private)
Functions that have been added:
1) addBinLinkPipe
2) addBinLinkPump
3) addBinLinkValve
4) addBinLink(Private)
5) str_make(Private)
> 4 Functions updated. 5 Functions added.
